/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -T wall.glb 
Files: wall.glb [13.95KB] > /mnt/c/Users/shado/projects/s24/capstone24/blender/runner_game/wall-transformed.glb [1.73KB] (88%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

function LightBar(props) {
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={new THREE.BoxGeometry(1.5, 0.25, 1.5)}
      >
        <meshBasicMaterial 
          color="#e83b3b"
        />
        <pointLight color="#e83b3b" power={50} />
      </mesh>
    </group>
  )
}

export function Wall(props) {
  const { nodes, materials } = useGLTF('/gltf/wall-transformed.glb')
  return (
    <group {...props} scale={0.325} rotation={[0, Math.PI, 0]} dispose={null} ref={props.innerRef}>
      <mesh 
        geometry={nodes.Wall.geometry} 
        material={nodes.Wall.material} 
        position={[0, 1.5, 0]} 
        scale={[0.6, 1.5, 0.25]} 
      >
        <LightBar position={[0, 2.65, 0]}/>
        {/* <LightBar position={[0, 1.5, 0]}/>
        <LightBar position={[0, 0.35, 0]}/> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/gltf/wall-transformed.glb')
