/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Canister.glb -T --keepmeshes 
Files: Canister.glb [1.11MB] > /mnt/c/Users/shado/projects/s24/capstone24/blender/runner_game/Canister/Canister-transformed.glb [154KB] (86%)
*/

import React from 'react'
import { Billboard, useGLTF, Image } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame } from '@react-three/fiber'

export function Canister(props) {
  const { nodes, materials } = useGLTF('/gltf/Canister-transformed.glb')

  useFrame(() => {
    props.innerRef.current.rotation.y += 0.025
  })

  return (
    <group {...props} ref={props.innerRef} scale={0.2} /* time={0} */ dispose={null}>
      <mesh geometry={nodes.Caps.geometry} material={materials.BrushedMetal} />
      <mesh geometry={nodes.Cylinder.geometry}>
        <meshBasicMaterial color={props.color} side={THREE.BackSide} transparent />
      </mesh>
      <Billboard rotateX={Math.PI}>
        <Image url={props.url} transparent scale={props.imageScale || 1.5} />
      </Billboard>
    </group>
  )
}

useGLTF.preload('/gltf/Canister-transformed.glb')
