/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -T coupling.glb 
Files: coupling.glb [3.47KB] > coupling-transformed.glb [1.08KB] (69%)
*/

import React from 'react'
import { Clone, useGLTF } from '@react-three/drei'
import { useSpring, animated } from '@react-spring/three'

function Couplings(props) {
  const { nodes } = useGLTF('/gltf/coupling-transformed.glb')
  const clones = []
  const pieces = 12
  const width = 16

  const { posZ } = useSpring({
    from: {
      posZ: [0, 0, 0]
    },
    to: {
      posZ: [0, 0, width - 1.25]
    },
    config: {
      duration: 1000
    },
    loop: true
  })

  for (let i = 0; i < pieces; i++) {
    clones.push(
      <Clone
        key={i}
        object={nodes.Coupling}
        position={[0, -3.35, -i * width]}
        inject={
          <meshStandardMaterial 
            metalness={0.85}
            roughness={0.1}
            color={"#ffffff"}
          />
        }
      />
    )
  }

  return (
    <animated.group scale={[0.37, 0.3, 0.3]} position={posZ}>
      {clones}
    </animated.group>
  )
}

export default Couplings

useGLTF.preload('/gltf/coupling-transformed.glb')
